name: Random Image Post

on:
  workflow_dispatch:
    # https://console.cron-job.org/ for schedule

jobs:
  post-waifu:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6.2.0
        with:
          node-version: '24'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build TypeScript
        run: npm run build

      - name: Check valid webhook URLs
        env:
          SFW_WEBHOOK_URL: ${{ secrets.SFW_WEBHOOK_URL }}
          NSFW_WEBHOOK_URL: ${{ secrets.NSFW_WEBHOOK_URL }}
        run: |
          if [ -z "$SFW_WEBHOOK_URL" ]; then
            echo "Error: SFW_WEBHOOK_URL is not set"
            exit 1
          fi
          if [ -z "$NSFW_WEBHOOK_URL" ]; then
            echo "Error: NSFW_WEBHOOK_URL is not set"
            exit 1
          fi

      - name: Post random images
        env:
          SFW_WEBHOOK_URL: ${{ secrets.SFW_WEBHOOK_URL }}
          NSFW_WEBHOOK_URL: ${{ secrets.NSFW_WEBHOOK_URL }}
          # If you use Danbooru
          DANBOORU_USERNAME: ${{ secrets.DANBOORU_USERNAME }}
          DANBOORU_API_KEY: ${{ secrets.DANBOORU_API_KEY }}
        run: |
            npm start -- --sfw --random-tags --source random
            npm start -- --nsfw --random-tags --source random
        shell: bash
